// <auto-generated />
using System;
using ContractOrganizer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ContractOrganizer.Migrations
{
    [DbContext(typeof(ContractOrganizerContext))]
    partial class ContractOrganizerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ContractOrganizer.Models.Attendance", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("labourid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("labourid");

                    b.ToTable("Attendance");
                });

            modelBuilder.Entity("ContractOrganizer.Models.Contract", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Company")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("labourid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("labourid");

                    b.ToTable("Contract");
                });

            modelBuilder.Entity("ContractOrganizer.Models.Labour", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dTime")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("Labour");
                });

            modelBuilder.Entity("ContractOrganizer.Models.admin", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("admin");
                });

            modelBuilder.Entity("ContractOrganizer.Models.Attendance", b =>
                {
                    b.HasOne("ContractOrganizer.Models.Labour", "labour")
                        .WithMany()
                        .HasForeignKey("labourid");

                    b.Navigation("labour");
                });

            modelBuilder.Entity("ContractOrganizer.Models.Contract", b =>
                {
                    b.HasOne("ContractOrganizer.Models.Labour", "labour")
                        .WithMany()
                        .HasForeignKey("labourid");

                    b.Navigation("labour");
                });
#pragma warning restore 612, 618
        }
    }
}
